services:
  django-webapp:
    container_name: django-app-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    ports:
      - 8080:${PORT}
    networks:
      - playground-network

networks:
  playground-network:
    external: true
